#############################
# YAML CONFIG
#############################
server:
  name: mqttRoute
  restAddr: 0.0.0.0
  restPort: 8096
  rpcAddr: 0.0.0.0
  rpcPort: 8095

logger:
  drive: zap_std
  path: log
  file: server.log
  level: 1

mysql:
  name: config
  host: 127.0.0.1
  port: 3306
  user: root
  password: s
  db: config

redis:
  host: 127.0.0.1
  port: 10080
  password: 123456

jaeger:
  agent: 10.0.3.76:6831
  sampling: http://10.0.3.76:5778/sampling
  serviceName: mqttRoute
  LogSpan: true