#############################
# YAML CONFIG
#############################
server:
  name: gobase
  restAddr: 0.0.0.0
  restPort: 8096
  rpcAddr: 0.0.0.0
  rpcPort: 8095

logger:
  drive: zap_std
  path: log
  file: server.log
  level: 1

mysql:
  name: config
  host: 127.0.0.1
  port: 3306
  user: root
  password: s
  db: config

redis:
  host: 127.0.0.1
  port: 10080
  password: 123456

jaeger:
  agent: 127.0.0.1:6831
  sampling: http://127.0.0.1:5778/sampling
  serviceName: gobase
  logSpan: false